# Generated by Django 5.1.5 on 2025-02-01 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_authority'),
        ('reservations', '0002_remove_reservation_total_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='authority',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('credit_card', 'Credit Card'), ('paypal', 'PayPal'), ('farsi_gateway', 'Farsi Payment Gateway')], default='credit_card', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='reservation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='reservations.reservation'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
