# Generated by Django 5.1.5 on 2025-02-01 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_remove_payment_authority_remove_payment_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='callback_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('credit_card', 'Credit Card'), ('paypal', 'PayPal'), ('zarinpal', 'Zarinpal')], default='credit_card', max_length=20),
        ),
    ]
