# Generated by Django 5.1.5 on 2025-02-03 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_remove_reservation_total_price_and_more'),
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name': 'Reservation', 'verbose_name_plural': 'Reservations'},
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='check_in',
            new_name='check_in_date',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='check_out',
            new_name='check_out_date',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='guests',
        ),
        migrations.AddField(
            model_name='reservation',
            name='num_of_people',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reservation',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='meal_option',
            field=models.CharField(choices=[('no_meal', 'No Meal'), ('breakfast', 'Breakfast'), ('half_board', 'Half Board'), ('full_board', 'Full Board')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
