# Generated by Django 5.1.5 on 2025-02-04 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_alter_reservation_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Meal Plan',
                'verbose_name_plural': 'Meal Plans',
            },
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='check_in_date',
            new_name='check_in',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='check_out_date',
            new_name='check_out',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='meal_option',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='num_of_people',
        ),
        migrations.AddField(
            model_name='reservation',
            name='guests',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='reservation',
            name='meal_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.mealplan'),
        ),
    ]
